# -*- coding: utf-8 -*-
import unittest
from crawler import crawl_web


class Tests(unittest.TestCase):

    def test(self):

        def loop(inp, out):
            for i in range(len(inp)-1):
                self.assertEqual(inp[i], out[i])
        input1 = crawl_web("https://sayamkanwar.com/")
        output1 = (['https://sayamkanwar.com/work', 'https://sayamkanwar.com/about', 'https://www.facebook.com/sayamkanwar', 'https://github.com/sayamkanwar', 'https://codepen.io/sayamk/', 'https://medium.com/@sayamkanwar/', 'https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900'], ['Sayam Kanwar'], '<!DOCTYPE html><html><head><title>Sayam Kanwar</title><meta charset="UTF-8"><meta name="author" content="Sayam Kanwar"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body><div class="main"><center><div class="overlay"></div></center> <br><div class="container"><h1>Hi, I\'m Sayam Kanwar</h1><p>Web Developer | Hacker | Designer</p> <a class="work" href="https://sayamkanwar.com/work">View My Work</a> <a class="about" href="https://sayamkanwar.com/about">About Me</a></div></div><br><center><div class="contact"><p class="p1">Interested in working with me? Let\'s make the internet great again.</p><div class="social"> <a href="mailto:mail@sayamkanwar.com" id="mail"><i class="fas fa-envelope"></i></a><a href="https://www.facebook.com/sayamkanwar" id="fb"><i class="fab fa-facebook"></i></a><a href="https://github.com/sayamkanwar" id="git"><i class="fab fa-github"></i></a><a href="https://codepen.io/sayamk/" id="cp"><i class="fab fa-codepen"></i></a><a href="https://medium.com/@sayamkanwar/" id="medium"><i class="fab fa-medium"></i></a></div><div class="space"></div></div> <br><p class="footer">Made with <span><i class="fas fa-heart"></i></span> by Sayam Kanwar</p></center><link rel="stylesheet" type="text/css" href="css/style.css"><link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet"> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script> <script type="text/javascript" src="js/script.js"></script> </body></html>')
        input2 = crawl_web("https://xino.in/osmarathon/")
        output2 = (['https://www.facebook.com/events/2334735946595200/'], ['Open Source Marathon | XINO 2019'], '<!DOCTYPE html>\n<html>\n<head>\n\t<title>Open Source Marathon | XINO 2019</title>\n\t<link rel="stylesheet" type="text/css" href="style.css">\n</head>\n<body>\n<div class="topbar">\n\t\t\t<div class="full">\n\t\t\t\t<a href="reg.php">\n\t\t\t\t<div class="leaderboard"> Sign up </div>\n\t\t\t\t</a>\n\t\t\t\t<a href="https://www.facebook.com/events/2334735946595200/">\n\t\t\t\t<div class="logout"> Facebook </div>\n\t\t\t\t</a>\n\t\t\t\t<div class="thead">Open Source Marathon</div>\n\t\t\t</div>\n\t\t</div>\n<br>\n<center>\n<div class="signin">\n<h1>Sign in</h1>\n<form action="signin.php" method="post">\n\t<input type="email" name="email" placeholder="Email" required><br>\n\t<input type="password" name="password" placeholder="Password" required><br>\n\t<input style="width: 340px;" type="submit" name="submit">\n</form>\n</div>\n</center>\n</body>\n</html>')
        input3 = crawl_web("https://oorjitchowdhary.github.io/")
        output3 = (['https://oorjitchowdhary.github.io/', 'https://oorjitchowdhary.github.io/assets/css/style.css?v=6b3796f32431eed2e4ee370dc0b1efceb468bfae', 'https://oorjitchowdhary.github.io/'], ['oorjitchowdhary.me | oorjitchowdhary.github.io'], '<!DOCTYPE html>\n<html lang="en-US">\n  <head>\n    <meta charset="UTF-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n\n<!-- Begin Jekyll SEO tag v2.5.0 -->\n<title>oorjitchowdhary.me | oorjitchowdhary.github.io</title>\n<meta name="generator" content="Jekyll v3.7.4" />\n<meta property="og:title" content="oorjitchowdhary.me" />\n<meta property="og:locale" content="en_US" />\n<link rel="canonical" href="https://oorjitchowdhary.github.io/" />\n<meta property="og:url" content="https://oorjitchowdhary.github.io/" />\n<meta property="og:site_name" content="oorjitchowdhary.github.io" />\n<script type="application/ld+json">\n{"headline":"oorjitchowdhary.me","@type":"WebSite","url":"https://oorjitchowdhary.github.io/","name":"oorjitchowdhary.github.io","@context":"http://schema.org"}</script>\n<!-- End Jekyll SEO tag -->\n\n    <link rel="stylesheet" href="/assets/css/style.css?v=6b3796f32431eed2e4ee370dc0b1efceb468bfae">\n  </head>\n  <body>\n    <div class="container-lg px-3 my-5 markdown-body">\n      \n      <h1><a href="https://oorjitchowdhary.github.io/">oorjitchowdhary.github.io</a></h1>\n      \n\n      <h1 id="oorjitchowdharyme">oorjitchowdhary.me</h1>\n<p>Work in progress. ⚒</p>\n\n\n      \n    </div>\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/anchor-js/4.1.0/anchor.min.js" integrity="sha256-lZaRhKri35AyJSypXXs4o6OPFTbTmUoltBbDCbdzegg=" crossorigin="anonymous"></script>\n    <script>anchors.add();</script>\n    \n  </body>\n</html>\n')
        loop(input1, output1)
        loop(input2, output2)
        loop(input3, output3)

if __name__ == '__main__':
    unittest.main()
